import * as XLSX from "xlsx";

/**
 * BRANDING & UTILS
 */
const BRAND = {
  name: "EXBD Group",
  subtitle: "Sovereign ERP Engine",
  color: "#10b981",
  dark: "#064e3b",
};

function sar(n: number | null | undefined): string {
  return (n || 0).toLocaleString("en", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function baseStyles(): string {
  return `
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'Inter','Segoe UI',system-ui,sans-serif;color:#1a1a1a;padding:30px 40px;font-size:12px;line-height:1.5}
    .header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:20px;padding-bottom:15px;border-bottom:3px solid ${BRAND.color}}
    .header h1{font-size:20px;color:${BRAND.dark};margin-bottom:2px}
    .header .sub{color:#666;font-size:11px}
    .header .brand{text-align:right;color:#999;font-size:10px}
    .meta{display:flex;gap:20px;margin-bottom:15px;font-size:11px;color:#666}
    .meta b{color:#333}
    table{width:100%;border-collapse:collapse;margin-bottom:15px;font-size:11px}
    th{background:#f0fdf4;padding:7px 8px;text-align:left;font-weight:700;border-bottom:2px solid #d1fae5;font-size:10px;text-transform:uppercase;letter-spacing:.5px;color:#065f46}
    td{padding:6px 8px;border-bottom:1px solid #f0f0f0}
    tr:hover{background:#fafafa}
    .r{text-align:right} .c{text-align:center} .mono{font-family:'Courier New',monospace}
    .totals-row td,.totals-row th{background:#ecfdf5;font-weight:700;border-top:2px solid ${BRAND.color};color:${BRAND.dark}}
    .section{margin-top:20px;margin-bottom:8px;font-size:13px;font-weight:700;color:${BRAND.dark};border-bottom:1px solid #e5e7eb;padding-bottom:4px}
    .footer{margin-top:30px;padding-top:10px;border-top:1px solid #e5e7eb;font-size:9px;color:#999;text-align:center}
    .badge{display:inline-block;padding:2px 8px;border-radius:10px;font-size:9px;font-weight:700}
    .badge-red{background:#fef2f2;color:#dc2626} .badge-green{background:#f0fdf4;color:#16a34a}
    .badge-yellow{background:#fefce8;color:#ca8a04} .badge-blue{background:#eff6ff;color:#2563eb}
    .kpi-row{display:flex;gap:15px;margin-bottom:15px}
    .kpi{flex:1;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:12px;text-align:center}
    .kpi .val{font-size:22px;font-weight:700;color:${BRAND.dark}} .kpi .lbl{font-size:9px;color:#666;text-transform:uppercase;margin-top:2px}
    @media print{body{padding:15px 20px} @page{size:A4 landscape;margin:10mm}}
  `;
}

function renderHeader(title: string, subtitle?: string): string {
  const now = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  return `<div class="header">
    <div><h1>${title}</h1><div class="sub">${subtitle || ""}</div></div>
    <div class="brand">${BRAND.name}<br>${BRAND.subtitle}<br>Generated: ${now}</div>
  </div>`;
}

function renderFooter(): string {
  return `<div class="footer">This document was generated by ${BRAND.name} ${BRAND.subtitle}. Confidential — for internal use only.</div>`;
}

function openPrintWindow(html: string) {
  const w = window.open("", "_blank");
  if (w) {
    w.document.write(`<!DOCTYPE html><html><head><style>${baseStyles()}</style></head><body>${html}<script>window.onload=function(){window.print()}<\/script></body></html>`);
    w.document.close();
  }
}

/**
 * EXPORT FUNCTIONS (XLSX/CSV)
 */
export function exportToXLSX(data: Record<string, any>[], fileName: string, sheetName = "Report") {
  const ws = XLSX.utils.json_to_sheet(data);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName);
  XLSX.writeFile(wb, `${fileName}.xlsx`);
}

/**
 * PDF GENERATORS
 */

export function pdfWorkerMaster(workers: any[]) {
  const rows = workers.map(w => `<tr>
    <td class="mono">${w.emp_id || "—"}</td><td>${w.name_en || "—"}</td><td>${w.iqama_no || "—"}</td>
    <td>${w.nationality || "—"}</td><td>${w.designation || w.occupation_en || "—"}</td>
    <td>${w.clients?.legal_name || "Unassigned"}</td><td>${w.work_status || "Active"}</td>
    <td class="r mono">${sar(w.basic_salary)}</td><td>${w.mobile || "—"}</td>
  </tr>`).join("");
  openPrintWindow(`${renderHeader("Worker Master Report", `Total: ${workers.length} workers`)}
    <table><thead><tr><th>EMP ID</th><th>Name</th><th>Iqama</th><th>Nationality</th><th>Designation</th><th>Client</th><th>Status</th><th class="r">Basic (SAR)</th><th>Mobile</th></tr></thead><tbody>${rows}</tbody></table>${renderFooter()}`);
}

export function pdfDocumentExpiry(workers: any[]) {
  const now = new Date();
  const items = workers.map(w => {
    const docs: any[] = [];
    if (w.iqama_expiry) docs.push({ type: "Iqama", no: w.iqama_no, expiry: w.iqama_expiry });
    if (w.passport_expiry_date) docs.push({ type: "Passport", no: w.passport_no, expiry: w.passport_expiry_date });
    if (w.health_insurance_expiry) docs.push({ type: "Health Insurance", no: w.health_insurance_no, expiry: w.health_insurance_expiry });
    return docs.map(d => ({ ...d, name: w.name_en, emp_id: w.emp_id, days: Math.ceil((new Date(d.expiry).getTime() - now.getTime()) / 86400000) }));
  }).flat().filter(d => d.days <= 90).sort((a, b) => a.days - b.days);

  const rows = items.map(d => {
    const cls = d.days <= 0 ? "badge-red" : d.days <= 30 ? "badge-yellow" : "badge-green";
    const label = d.days <= 0 ? "EXPIRED" : `${d.days}d left`;
    return `<tr><td>${d.name}</td><td class="mono">${d.emp_id || "—"}</td><td>${d.type}</td><td class="mono">${d.no || "—"}</td><td>${d.expiry}</td><td class="c"><span class="badge ${cls}">${label}</span></td></tr>`;
  }).join("");
  openPrintWindow(`${renderHeader("Document Expiry Report", `${items.length} documents expiring within 90 days`)}
    <table><thead><tr><th>Worker</th><th>EMP ID</th><th>Document</th><th>Number</th><th>Expiry</th><th class="c">Status</th></tr></thead><tbody>${rows}</tbody></table>${renderFooter()}`);
}

export function pdfBenchWorkers(workers: any[]) {
  const bench = workers.filter(w => !w.client_id && (w.work_status || "active").toLowerCase() !== "terminated");
  const rows = bench.map(w => `<tr><td class="mono">${w.emp_id || "—"}</td><td>${w.name_en || "—"}</td><td>${w.nationality || "—"}</td><td>${w.designation || w.occupation_en || "—"}</td><td class="r mono">${sar(w.basic_salary)}</td><td>${w.joining_date || "—"}</td></tr>`).join("");
  openPrintWindow(`${renderHeader("Bench Worker Report", `${bench.length} unassigned workers`)}
    <table><thead><tr><th>EMP ID</th><th>Name</th><th>Nationality</th><th>Designation</th><th class="r">Basic (SAR)</th><th>Joined</th></tr></thead><tbody>${rows}</tbody></table>${renderFooter()}`);
}

export function pdfLiabilityLogs(liabilities: any[]) {
  const rows = liabilities.map(l => `<tr><td>${l.workers?.name_en || "—"}</td><td class="mono">${l.workers?.emp_id || "—"}</td><td>${l.liability_name || "—"}</td><td class="r mono">${sar(l.total_amount)}</td><td class="r mono">${sar(l.recovered_amount)}</td><td class="r mono">${sar((l.total_amount || 0) - (l.recovered_amount || 0))}</td><td><span class="badge ${l.status === "paid" ? "badge-green" : "badge-yellow"}">${l.status}</span></td></tr>`).join("");
  openPrintWindow(`${renderHeader("Liability Logs", `${liabilities.length} records`)}
    <table><thead><tr><th>Worker</th><th>EMP ID</th><th>Type</th><th class="r">Total</th><th class="r">Recovered</th><th class="r">Remaining</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table>${renderFooter()}`);
}

export function pdfTrialBalance(entries: any[]) {
  let totalDr = 0, totalCr = 0;
  const rows = entries.map(e => { totalDr += e.debit; totalCr += e.credit; return `<tr><td class="mono">${e.code}</td><td>${e.name}</td><td>${e.type}</td><td class="r mono">${sar(e.debit)}</td><td class="r mono">${sar(e.credit)}</td></tr>`; }).join("");
  openPrintWindow(`${renderHeader("Trial Balance")}
    <table><thead><tr><th>Code</th><th>Account</th><th>Type</th><th class="r">Debit (SAR)</th><th class="r">Credit (SAR)</th></tr></thead><tbody>${rows}</tbody>
    <tfoot><tr class="totals-row"><td colspan="3">Total</td><td class="r mono">${sar(totalDr)}</td><td class="r mono">${sar(totalCr)}</td></tr></tfoot></table>${renderFooter()}`);
}

export function pdfProfitLoss(pl: any[]) {
  const rev = pl.filter(r => r.type === "revenue");
  const exp = pl.filter(r => r.type === "expense");
  const totalRev = rev.reduce((s, r) => s + r.amount, 0);
  const totalExp = exp.reduce((s, r) => s + r.amount, 0);
  const makeRows = (items: any[]) => items.map(r => `<tr><td class="mono">${r.code}</td><td>${r.name}</td><td class="r mono">${sar(r.amount)}</td></tr>`).join("");
  openPrintWindow(`${renderHeader("Profit & Loss Statement")}
    <div class="section">Revenue</div><table><thead><tr><th>Code</th><th>Account</th><th class="r">Amount (SAR)</th></tr></thead><tbody>${makeRows(rev)}</tbody><tfoot><tr class="totals-row"><td colspan="2">Total Revenue</td><td class="r mono">${sar(totalRev)}</td></tr></tfoot></table>
    <div class="section">Expenses</div><table><thead><tr><th>Code</th><th>Account</th><th class="r">Amount (SAR)</th></tr></thead><tbody>${makeRows(exp)}</tbody><tfoot><tr class="totals-row"><td colspan="2">Total Expenses</td><td class="r mono">${sar(totalExp)}</td></tr></tfoot></table>
    <div class="kpi-row"><div class="kpi"><div class="val" style="color:${totalRev - totalExp >= 0 ? "#16a34a" : "#dc2626"}">${sar(totalRev - totalExp)}</div><div class="lbl">Net Income</div></div></div>${renderFooter()}`);
}

export function pdfBalanceSheet(bs: any[]) {
  const groups = ["asset", "liability", "equity"];
  const sections = groups.map(g => {
    const items = bs.filter(b => b.type === g);
    const total = items.reduce((s, b) => s + b.balance, 0);
    const rows = items.map(b => `<tr><td class="mono">${b.code}</td><td>${b.name}</td><td class="r mono">${sar(b.balance)}</td></tr>`).join("");
    return `<div class="section">${g.charAt(0).toUpperCase() + g.slice(1)}s</div><table><thead><tr><th>Code</th><th>Account</th><th class="r">Balance (SAR)</th></tr></thead><tbody>${rows}</tbody><tfoot><tr class="totals-row"><td colspan="2">Total ${g}s</td><td class="r mono">${sar(total)}</td></tr></tfoot></table>`;
  }).join("");
  openPrintWindow(`${renderHeader("Balance Sheet")}${sections}${renderFooter()}`);
}

export function pdfGenericTable(title: string, subtitle: string, columns: any[], data: any[]) {
  const ths = columns.map(c => `<th class="${c.align === "right" ? "r" : ""}">${c.label}</th>`).join("");
  const rows = data.map(r => `<tr>${columns.map(c => `<td class="${c.align === "right" ? "r" : ""} ${c.mono ? "mono" : ""}">${r[c.key] ?? "—"}</td>`).join("")}</tr>`).join("");
  openPrintWindow(`${renderHeader(title, subtitle)}<table><thead><tr>${ths}</tr></thead><tbody>${rows}</tbody></table>${renderFooter()}`);
}

export function pdfNonIqamaClients(workers: any[]) {
  const nonIqama = workers.filter(w => w.client_id && !w.iqama_no);
  pdfGenericTable("Non-Iqama Clients Report", `${nonIqama.length} workers assigned to clients without Iqama`, [
    {key:"name_en", label:"Worker Name"},
    {key:"emp_id", label:"EMP ID", mono:true},
    {key:"clients.legal_name", label:"Client"},
    {key:"nationality", label:"Nationality"}
  ], nonIqama.map(w => ({ ...w, "clients.legal_name": w.clients?.legal_name })));
}

export function pdfVehicleFleet(assets: any[]) {
  pdfGenericTable("Vehicle Fleet Report", `${assets.length} vehicles`, [
    {key:"asset_code", label:"Asset Code", mono:true},
    {key:"name", label:"Vehicle Name"},
    {key:"brand", label:"Brand"},
    {key:"model", label:"Model"},
    {key:"serial_number", label:"Plate Number"},
    {key:"clients.legal_name", label:"Assigned Client"}
  ], assets.map(a => ({ ...a, "clients.legal_name": a.clients?.legal_name })));
}

export function pdfAssetInventory(assets: any[]) {
  pdfGenericTable("Asset Inventory", `${assets.length} total assets`, [
    {key:"asset_code", label:"Code", mono:true},
    {key:"name", label:"Name"},
    {key:"category", label:"Category"},
    {key:"purchase_price", label:"Purchase Price", align:"right"},
    {key:"current_value", label:"Current Value", align:"right"},
    {key:"status", label:"Status"}
  ], assets);
}

export function pdfClientProfitability(data: any[]) {
  pdfGenericTable("Client Profitability Report", "Profit margin analysis per client", [
    {key:"client", label:"Client"},
    {key:"revenue", label:"Revenue", align:"right"},
    {key:"cost", label:"Direct Cost", align:"right"},
    {key:"margin", label:"Net Margin", align:"right"},
    {key:"pct", label:"Margin %", align:"right"}
  ], data.map(d => ({
    ...d,
    revenue: sar(d.revenue),
    cost: sar(d.cost),
    margin: sar(d.margin),
    pct: d.pct.toFixed(1) + "%"
  })));
}
